### ISSUE TITLE
Will not run on SAMD21 M0 Express (specifically QT Py Haxpress)

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_DPS310#10]
We may want to look into refactoring this. Either that or we need to include some documentation either in the guide or the library explaining the limitations.

To replicate:
Copy the lib and its dependencies to the board. 

Code.py contents:
```
import adafruit_dps310
```
Results:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 3, in <module>
  File "adafruit_dps310.py", line 172, in <module>
  File "adafruit_dps310.py", line 418, in DPS310
MemoryError: memory allocation failed, allocating 376 bytes



Press any key to enter the REPL. Use CTRL-D to reload.soft reboot
```

**Comment by jposada202020** [comment]
Closed by #13 .
